// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizHub.Data;

#nullable disable

namespace QuizHub.Migrations
{
    [DbContext(typeof(QuizHubDbContext))]
    [Migration("20251126152813_AddMaDanhMucToBaiThi")]
    partial class AddMaDanhMucToBaiThi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("VaiTro_Claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NguoiDung_Claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("NguoiDung_DangNhapNgoai", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("NguoiDung_VaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("NguoiDung_Tokens", (string)null);
                });

            modelBuilder.Entity("QuizHub.Models.Entities.BaiThi", b =>
                {
                    b.Property<Guid>("MaBaiThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhBia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CheDoCongKhai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ChoPhepXemLai")
                        .HasColumnType("bit");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int?>("DiemDat")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiemTrungBinh")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("HienThiDapAnSauKhiNop")
                        .HasColumnType("bit");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<Guid?>("MaDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaTruyCapDinhDanh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ThoiGianLamBai")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TongLuotLamBai")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBaiThi");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaTruyCapDinhDanh")
                        .IsUnique();

                    b.HasIndex("NgayTao");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("MaTruyCapDinhDanh", "DaXoa");

                    b.HasIndex("CheDoCongKhai", "TrangThai", "DaXoa");

                    b.HasIndex("DaXoa", "CheDoCongKhai", "TrangThai");

                    b.HasIndex("NguoiTaoId", "DaXoa", "NgayTao");

                    b.ToTable("BaiThi");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.BaiThiThe", b =>
                {
                    b.Property<Guid>("MaBaiThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaThe")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaBaiThi", "MaThe");

                    b.HasIndex("MaThe");

                    b.ToTable("BaiThiThe");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.BaoCao", b =>
                {
                    b.Property<Guid>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KetQuaXuLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiDoiTuong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaDoiTuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiBaoCaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NguoiXuLyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ThoiGianXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBaoCao");

                    b.HasIndex("NguoiBaoCaoId");

                    b.HasIndex("NguoiXuLyId");

                    b.HasIndex("LoaiDoiTuong", "MaDoiTuong");

                    b.HasIndex("TrangThai", "NgayTao");

                    b.ToTable("BaoCao");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.CauHoi", b =>
                {
                    b.Property<Guid>("MaCauHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CongKhai")
                        .HasColumnType("bit");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("GiaiThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiCauHoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("MaDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MucDo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NguonNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoiDungCauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCauHoi");

                    b.HasIndex("DaXoa");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("MaDanhMuc", "DaXoa");

                    b.HasIndex("NguoiTaoId", "MaDanhMuc");

                    b.HasIndex("DaXoa", "NguoiTaoId", "CongKhai");

                    b.HasIndex("NguoiTaoId", "DaXoa", "NgayTao");

                    b.ToTable("CauHoi");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.CauHoiTrongBaiThi", b =>
                {
                    b.Property<Guid>("MaCauHoiTrongBaiThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<Guid>("MaBaiThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaCauHoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaCauHoiTrongBaiThi");

                    b.HasIndex("MaCauHoi");

                    b.HasIndex("MaBaiThi", "MaCauHoi")
                        .IsUnique();

                    b.ToTable("CauHoiTrongBaiThi");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.CauTraLoi", b =>
                {
                    b.Property<Guid>("MaCauTraLoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LaDapAnDung")
                        .HasColumnType("bit");

                    b.Property<Guid>("MaCauHoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaLuaChonDaChon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaLuotLamBai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ThoiGianSuDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTraLoi")
                        .HasColumnType("datetime2");

                    b.HasKey("MaCauTraLoi");

                    b.HasIndex("MaCauHoi");

                    b.HasIndex("MaLuaChonDaChon");

                    b.HasIndex("MaLuotLamBai", "MaCauHoi");

                    b.ToTable("CauTraLoi");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.DanhGia", b =>
                {
                    b.Property<Guid>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaBaiThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("XepHang")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaBaiThi");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("MaBaiThi", "NguoiDungId")
                        .IsUnique();

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.DanhMuc", b =>
                {
                    b.Property<Guid>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("DuongDan")
                        .IsUnique();

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.LuaChonDapAn", b =>
                {
                    b.Property<Guid>("MaLuaChon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LaDapAnDung")
                        .HasColumnType("bit");

                    b.Property<Guid>("MaCauHoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungDapAn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaLuaChon");

                    b.HasIndex("MaCauHoi");

                    b.ToTable("LuaChonDapAn");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.LuotLamBai", b =>
                {
                    b.Property<Guid>("MaLuotLamBai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Diem")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("MaBaiThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NguoiDungId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoCauChuaLam")
                        .HasColumnType("int");

                    b.Property<int>("SoCauDung")
                        .HasColumnType("int");

                    b.Property<int>("SoCauSai")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiThamGia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ThoiGianLamBaiThucTe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianNopBai")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThongTinTrinhDuyet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TongSoCauHoi")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLuotLamBai");

                    b.HasIndex("MaBaiThi");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TrangThai");

                    b.HasIndex("MaBaiThi", "NguoiDungId");

                    b.HasIndex("TrangThai", "ThoiGianKetThuc");

                    b.HasIndex("MaBaiThi", "TrangThai", "Diem");

                    b.ToTable("LuotLamBai");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.NguoiDung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapNhatBoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("ProfileCongKhai")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuSu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiKichHoat")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QuizHub.Models.Entities.NhatKyHeThong", b =>
                {
                    b.Property<Guid>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GiaTriCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaTriMoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiDoiTuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaDoiTuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NguoiDungId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThongTinTrinhDuyet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.PhienNhapDuLieu", b =>
                {
                    b.Property<Guid>("MaPhien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("KichThuocTepTin")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiTepTin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoHinhAI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoCauHoiNhap")
                        .HasColumnType("int");

                    b.Property<int>("SoCauHoiTrichXuat")
                        .HasColumnType("int");

                    b.Property<string>("TenTepTin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ThoiGianXuLy")
                        .HasColumnType("int");

                    b.Property<string>("ThongBaoLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhien");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("PhienNhapDuLieu");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.The", b =>
                {
                    b.Property<Guid>("MaThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLanSuDung")
                        .HasColumnType("int");

                    b.Property<string>("TenThe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThe");

                    b.HasIndex("TenThe")
                        .IsUnique();

                    b.ToTable("The");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.ThongBao", b =>
                {
                    b.Property<Guid>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("MaDoiTuongLienQuan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("NgayTao");

                    b.HasIndex("NguoiDungId", "DaDoc");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizHub.Models.Entities.BaiThi", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("MaDanhMuc");

                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany("CacBaiThiDaTao")
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.BaiThiThe", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.BaiThi", "BaiThi")
                        .WithMany("CacThe")
                        .HasForeignKey("MaBaiThi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizHub.Models.Entities.The", "The")
                        .WithMany("CacBaiThi")
                        .HasForeignKey("MaThe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiThi");

                    b.Navigation("The");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.BaoCao", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiBaoCaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiXuLyId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("QuizHub.Models.Entities.CauHoi", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.DanhMuc", "DanhMuc")
                        .WithMany("CacCauHoi")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany("CacCauHoiDaTao")
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.CauHoiTrongBaiThi", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.BaiThi", "BaiThi")
                        .WithMany("CacCauHoi")
                        .HasForeignKey("MaBaiThi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizHub.Models.Entities.CauHoi", "CauHoi")
                        .WithMany("CacBaiThiChuaCauHoiNay")
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiThi");

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.CauTraLoi", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuizHub.Models.Entities.LuaChonDapAn", "LuaChonDaChon")
                        .WithMany()
                        .HasForeignKey("MaLuaChonDaChon")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuizHub.Models.Entities.LuotLamBai", "LuotLamBai")
                        .WithMany("CacCauTraLoi")
                        .HasForeignKey("MaLuotLamBai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("LuaChonDaChon");

                    b.Navigation("LuotLamBai");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.DanhGia", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.BaiThi", "BaiThi")
                        .WithMany("CacDanhGia")
                        .HasForeignKey("MaBaiThi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiThi");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.LuaChonDapAn", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.CauHoi", "CauHoi")
                        .WithMany("CacLuaChon")
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.LuotLamBai", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.BaiThi", "BaiThi")
                        .WithMany("CacLuotLamBai")
                        .HasForeignKey("MaBaiThi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany("CacLuotLamBai")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BaiThi");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.NhatKyHeThong", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("QuizHub.Models.Entities.PhienNhapDuLieu", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizHub.Models.Entities.ThongBao", b =>
                {
                    b.HasOne("QuizHub.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizHub.Models.Entities.BaiThi", b =>
                {
                    b.Navigation("CacCauHoi");

                    b.Navigation("CacDanhGia");

                    b.Navigation("CacLuotLamBai");

                    b.Navigation("CacThe");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.CauHoi", b =>
                {
                    b.Navigation("CacBaiThiChuaCauHoiNay");

                    b.Navigation("CacLuaChon");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.DanhMuc", b =>
                {
                    b.Navigation("CacCauHoi");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.LuotLamBai", b =>
                {
                    b.Navigation("CacCauTraLoi");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.NguoiDung", b =>
                {
                    b.Navigation("CacBaiThiDaTao");

                    b.Navigation("CacCauHoiDaTao");

                    b.Navigation("CacLuotLamBai");
                });

            modelBuilder.Entity("QuizHub.Models.Entities.The", b =>
                {
                    b.Navigation("CacBaiThi");
                });
#pragma warning restore 612, 618
        }
    }
}
